### ISSUE TITLE
RN Web support?

### ISSUE THREAD

**Issue by samburgers** [tienphaw/react-native-capsize#1]
Appears to break on RN Web, any plans for support? Or documenting a workaround? Cheers!

**Comment by phamfoo** [comment]
Hi @samburgers,
I just published a new version with web support (~~v0.2.0~~ v0.2.1), can you give it a try?

**Comment by samburgers** [comment]
Nice one! just tested, doesn't seem to be quite there

![Screen Shot 2020-11-05 at 3 09 17 pm](https://user-images.githubusercontent.com/1476939/98189001-f3b20980-1f78-11eb-9d63-75eada29c009.png)

**Comment by samburgers** [comment]
Just tested, works well, thanks so much!
