### ISSUE TITLE
[Android] Negative margin issues

### ISSUE THREAD

**Issue by jossmac** [tienphaw/react-native-capsize#2]
I'm not 100% on the cause, but it seems related to [this note in the docs](https://reactnative.dev/docs/0.67/style#known-issues).

### Solution

I'm using the `CapHeightWithLeading` code path and am able to resolve the issue by tweaking the margins, which seem to be off by 2x:

```js
const styles = capsize({
  capHeight,
  fontMetrics,
  leading,
});

// platform specifics omitted for brevity
const adjustedStyles = {
  ...styles,
  marginTop: styles.marginTop * 2,
  marginBottom: styles.marginBottom * 0.5,
}
```

| Before | After |
| ------ | ----- |
| <img width="365" alt="Screenshot o Android device illustrating leading issue" src="https://user-images.githubusercontent.com/2730833/162130772-efb145a4-a24f-4463-ab1d-fed52e5223e1.png"> | <img width="365" alt="Screenshot of Android device illustrating leading issue resolution" src="https://user-images.githubusercontent.com/2730833/162130918-9002ad4c-5c2c-4545-be11-6f185a365c9d.png"> |

### Considerations

Not sure if it's relevant, but the font metrics I'm using yield a `paddingTop` value of `0`:

```js
{
  capHeight: 710,
  ascent: 710,
  descent: -210,
  lineGap: 0,
  unitsPerEm: 1000,
}
```

**Comment by phamfoo** [comment]
Have you tried the workaround in this comment https://github.com/facebook/react-native/issues/29232#issuecomment-926271953?

**Comment by jossmac** [comment]
Sorted, thanks @tienphaw
